### ISSUE TITLE
Wrong route retrieved

### ISSUE THREAD

**Issue by aurelbe** [vmichalak/Hermes.Net#1]
Hello,

When I create 2 routes in this order:

``` csharp
server.AddGetRoute("/", new SampleMiddleWare());
server.AddTransparentFolderRoute("/style", storageFolder);
```

and try to access to a file in the second route with the url '/style/style.css', I always get the content of the first route.
However, if I write these 2 lines in this order:

``` csharp
server.AddTransparentFolderRoute("/style", storageFolder);
server.AddGetRoute("/", new SampleMiddleWare());
```

everything seems to work fine.

Is this a bug or am I using it wrong ?

For information, the bug seems to be located in the FilterMiddlewares method of the MiddlewareManager class.

Kind Regards,

Aurelien

**Comment by vmichalak** [comment]
Hi orel91,
Thanks you for your feedback, it's really a bug in hermes.net.
I correct it in the new build, you can download it directly on NuGet if you want.
Kind Regards,
Valentin Michalak
